[build]
  publish = "client/build"
  command = "npm run build --prefix client"

[dev]
  command = "npm run dev --prefix client"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
